#!/usr/bin/env bash

while :
do
  curl --request POST \
  --url http://localhost:8080/v1/t \
  --header 'authorization: TmpuUzhORm9HSmpKSHNzNXM4eGZi' \
  --header 'content-type: application/json' \
  --data '{
    "appId": "NjnS8NFoGJjJHss5s8xf",
    "anonymousId": "cc26e54c-3595-4554-a232-18901baa4deb",
    "messageId": "1cd4e644-c856-4057-82fa-db73e50022c2",
    "sentAt": "2017-10-12T19:25:46.446Z",
    "type": "track",
    "userId": "597a4341167bfb0001bf30bc",
    "context": {
        "library": {
            "name": "analytics-node",
            "version": "3.0.13"
        },
        "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36",
        "page": {
            "path": "/org/591b68411a05d300018c7b73",
            "referrer": "",
            "search": "",
            "title": "Waiting...",
            "url": "https://alpha.astronomer.io/org/591b68411a05d300018c7b73"
        }
    },
    "integrations": {},
    "properties": {
        "goal": "User views event monitoring",
        "on": "click"
    },
    "timestamp": "2017-10-12T19:25:46.446Z"
}'
sleep 1
done
