---
############################################
## external-secrets: cluster secret store ##
############################################
{{- if eq .Values.global.plane.mode "data" }}
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.secretsBackend.clusterSecretStore.name }}
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.secretsBackend.clusterSecretStore.region }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            namespace: {{ .Release.Namespace }}
            name: {{ .Values.secretsBackend.credentials.name }}
            key: access-key
          secretAccessKeySecretRef:
            namespace: {{ .Release.Namespace }}
            name: {{ .Values.secretsBackend.credentials.name }}
            key: secret-access-key
{{- end }}
