---
###################################
# external-secrets extra objects ##
###################################
{{- if eq .Values.global.plane.mode "data" }}
{{- range .Values.extraObjects }}
---
##############################################
# external-secrets extra objects (rendered) ##
##############################################
{{ include "external-secrets.render" (dict "value" . "context" $) }}
{{- end }}
{{- end }}
