---
###########################################################################
# external-secrets extra objects
###########################################################################
{{- range .Values.extraObjects }}
---
###########################################################################
# external-secrets extra objects (rendered)
###########################################################################
{{ include "external-secrets.render" (dict "value" . "context" $) }}
{{- end }}
