---
###################################################
## external-secrets: secrets backend credentials ##
###################################################

{{- if eq .Values.global.plane.mode "data" }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.secretsBackend.credentials.name }}
  namespace: {{ .Release.Namespace }}
data:
  access-key: {{ .Values.secretsBackend.credentials.accessKey | b64enc | quote }}
  secret-access-key: {{ .Values.secretsBackend.credentials.secretAccessKey | b64enc | quote }}
{{- end }}
