#####################
## Grafana Ingress ##
#####################
{{- if or (eq .Values.global.plane.mode "control") (eq .Values.global.plane.mode "unified") }}
{{- if .Values.global.baseDomain }}
kind: Ingress
apiVersion: {{ template "apiVersion.Ingress" . }}
metadata:
  name: {{ template "grafana.fullname" . }}-ingress
  labels:
    tier: grafana-networking
    component: grafana-ingress
    chart: {{ template "grafana.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- if .Values.global.authSidecar.enabled }}
    {{- toYaml .Values.global.extraAnnotations | nindent 4 }}
    {{- else }}
    kubernetes.io/ingress.class: "{{ .Release.Name }}-nginx"
    {{- if .Values.global.extraAnnotations }}
    {{- toYaml .Values.global.extraAnnotations | nindent 4 }}
    {{- end }}
    {{- include "houston.internalauthurl" . | indent 4}}
    nginx.ingress.kubernetes.io/auth-signin: https://app.{{ .Values.global.baseDomain }}/login
    nginx.ingress.kubernetes.io/auth-response-headers: authorization, username, email
    {{- end }}
spec:
  {{- if .Values.global.tlsSecret }}
  tls:
    - secretName: {{ .Values.global.tlsSecret }}
      hosts:
        - {{ template "grafana.url" . }}
        {{- if .Values.global.controlPlaneHA.enabled }}
        - {{ template "grafana.globalUrl" . }}
        {{- end }}
  {{- end }}
  rules:
    - host: {{ template "grafana.url" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "grafana.fullname" . }}
                port:
                  {{- if .Values.global.authSidecar.enabled }}
                  name: auth-proxy
                  {{- else }}
                  name: grafana-ui
                  {{- end }}
    {{- if .Values.global.controlPlaneHA.enabled }}
    - host: {{ template "grafana.globalUrl" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "grafana.fullname" . }}
                port:
                  {{- if .Values.global.authSidecar.enabled }}
                  name: auth-proxy
                  {{- else }}
                  name: grafana-ui
                  {{- end }}
    {{- end }}
{{- end }}
{{- end }}
