{{- if .Values.global.istioEnabled }}
{{- if or (eq .Values.global.plane.mode "control") (eq .Values.global.plane.mode "unified") }}
---
apiVersion: {{ template "apiVersion.istio.networking" . }}
kind: VirtualService
metadata:
  name: {{ template "grafana.fullname" . }}-virtualservice
  namespace: {{ .Release.Namespace }}
  labels:
    tier: grafana-networking
    component: grafana-virtualservice
    chart: {{ template "grafana.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  hosts:
  - "{{ template "grafana.url" . }}"
  gateways:
  - {{ .Values.global.istio.gateway }}
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: {{ template "grafana.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          {{- if .Values.global.authSidecar.enabled }}
          number: {{ .Values.global.authSidecar.port }}
          {{- else }}
          number: 3000
          {{- end }}
    {{- if .Values.global.istio.virtualService.timeout }}
    timeout: {{ .Values.global.istio.virtualService.timeout }}
    {{- end }}
    {{- if .Values.global.istio.virtualService.retries }}
    retries:
      {{- toYaml .Values.global.istio.virtualService.retries | nindent 6 }}
    {{- end }}
{{- end }}
{{- end }}
