##############################
## Pilot Service Account    ##
##############################
{{- if eq .Values.global.plane.mode "data" }}
{{- if and .Values.pilot.serviceAccount.create .Values.global.rbacEnabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "pilot.serviceAccountName" . }}
  labels:
    component: pilot
    tier: astronomer
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    plane: {{ .Values.global.plane.mode }}
  annotations:
    {{- with .Values.pilot.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
{{- end }}
