#####################
## Houston Ingress ##
#####################
{{- if .Values.global.baseDomain }}
{{- if or (eq .Values.global.plane.mode "control") (eq .Values.global.plane.mode "unified") }}
kind: Ingress
apiVersion: {{ template "apiVersion.Ingress" . }}
metadata:
  name: {{ .Release.Name }}-houston-ingress
  labels:
    component: houston-ingress
    tier: astronomer
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    plane: {{ .Values.global.plane.mode }}
  annotations:
    {{- if .Values.global.authSidecar.enabled  }}
{{- toYaml .Values.global.extraAnnotations | nindent 4 }}
    {{- else }}
    {{- if .Values.global.extraAnnotations }}
{{- toYaml .Values.global.extraAnnotations | nindent 4 }}
    {{- end }}
    kubernetes.io/ingress.class: "{{ .Release.Name }}-traefik"
    # proxy-buffer-size is translated by Traefik's NGINX ingress provider
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    traefik.ingress.kubernetes.io/router.middlewares: "{{ .Release.Namespace }}-{{ .Release.Name }}-custom-errors@kubernetescrd,{{ .Release.Namespace }}-{{ .Release.Name }}-security-headers@kubernetescrd"
    # /v1/alerts and /v1/metrics are blocked via IngressRoute CRDs in charts/traefik/templates/middleware-block-internal-routes.yaml
    {{- end }}

    {{- if .Values.houston.ingress.annotation  }}
    {{- toYaml .Values.houston.ingress.annotation  | nindent 4  }}
    {{- end }}
spec:
  {{- if .Values.global.tlsSecret }}
  tls:
    - secretName: {{ .Values.global.tlsSecret }}
      hosts:
        - houston.{{ .Values.global.baseDomain }}
  {{- end }}
  rules:
  - host: houston.{{ .Values.global.baseDomain }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}-houston
              port:
                name: houston-http
{{- end }}
{{- end }}
