{
 "title": "Airflow",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Scheduler Heartbeat",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "airflow_scheduler_heartbeat" }
   ]
  },
  {
   "title": "Collect DAGs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "airflow_collect_dags" }
   ]
  },
  {
   "title": "Dagbag Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "airflow_dagbag_size" }
   ]
  },
  {
   "title": "Ongoing Local Task Jobs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "airflow_localtaskjob_start - airflow_localtaskjob_end"
    }
   ]
  },
  {
   "title": "Successful Task Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "airflow_ti_successes" }
   ]
  },
  {
   "title": "Failed Task Instances",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "airflow_ti_failures" }
   ]
  },
  {
   "title": "Operator Successes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "airflow_operator_successes", "legendFormat": "{{operator}}" }
   ]
  },
  {
   "title": "Operator Failures",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "airflow_operator_failures", "legendFormat": "{{operator}}" }
   ]
  },
  {
   "title": "Dependency Checks q0.5",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "airflow_dagrun_dependency_check{quantile=\"0.5\"}",
     "legendFormat": "{{dag_id}}"
    }
   ]
  },
  {
   "title": "Dependency Checks q0.9",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "airflow_dagrun_dependency_check{quantile=\"0.9\"}",
     "legendFormat": "{{dag_id}}"
    }
   ]
  },
  {
   "title": "Dependency Checks q0.99",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "airflow_dagrun_dependency_check{quantile=\"0.99\"}",
     "legendFormat": "{{dag_id}}"
    }
   ]
  }
 ]
}