#############################
## Laminar Hypervisor RBAC ##
#############################
{{- if eq (include "laminar.enabled" .) "true" }}
{{- if .Values.global.rbac.enabled }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: laminar-hypervisor-airflows
  labels:
    {{- include "laminar.labels" (list $ "hypervisor") | nindent 4 }}
rules:
  - apiGroups: ["airflow.apache.org"]
    resources: ["airflows"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["airflow.apache.org"]
    resources:
      - airflows/status
      - schedulers
      - statsds
      - triggerers
      - redis
      - webservers
      - pgbouncers
      - dagprocessors
      - eventschedulers
      - apiservers
    verbs: ["get"]
  - apiGroups: ["airflow.apache.org"]
    resources:
      - schedulers/scale
      - statsds/scale
      - triggerers/scale
      - redis/scale
      - webservers/scale
      - pgbouncers/scale
      - dagprocessors/scale
      - eventschedulers/scale
      - apiservers/scale
    verbs: ["*"]
  - apiGroups: ["apps"]
    resources: ["deployments", "deployments/status"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "delete", "deletecollection"]
  - apiGroups: [""]
    resources: ["pods/status"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["keda.sh"]
    resources: ["scaledobjects"]
    verbs: ["get", "list", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: laminar-hypervisor-airflows
  labels:
    {{- include "laminar.labels" (list $ "hypervisor") | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: laminar-hypervisor-airflows
subjects:
  - kind: ServiceAccount
    name: {{ include "laminar.serviceAccountName" (list $ "hypervisor") }}
    namespace: {{ .Release.Namespace }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: laminar-hypervisor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "laminar.labels" (list $ "hypervisor") | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["serviceaccounts/token"]
    verbs: ["create"]
    resourceNames: ["hypervisor"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: laminar-hypervisor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "laminar.labels" (list $ "hypervisor") | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: laminar-hypervisor
subjects:
  - kind: ServiceAccount
    name: {{ include "laminar.serviceAccountName" (list $ "hypervisor") }}
    namespace: {{ .Release.Namespace }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: laminar-airflow-configmaps
  labels:
    {{- include "laminar.labels" (list $ "hypervisor") | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: laminar-airflow-configmaps
  labels:
    {{- include "laminar.labels" (list $ "hypervisor") | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: laminar-airflow-configmaps
subjects:
  - kind: ServiceAccount
    name: {{ include "laminar.serviceAccountName" (list $ "hypervisor") }}
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
