##############################
## Traefik Service Account  ##
##############################
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "traefik.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    tier: traefik
    component: traefik-serviceaccount
    chart: {{ template "traefik.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
