##########################################
## Traefik Default Backend ServiceAccount ##
##########################################
{{- if .Values.defaultBackend.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "traefik.defaultBackend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    tier: traefik
    component: traefik-default-backend
    chart: {{ template "traefik.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- end }}
