{{- if .Values.global.istioEnabled }}
{{- if or (eq .Values.global.plane.mode "control") (eq .Values.global.plane.mode "unified") }}
---
apiVersion: {{ template "apiVersion.istio.networking" . }}
kind: VirtualService
metadata:
  name: {{ template "prometheus.fullname" . }}-virtualservice
  namespace: {{ .Release.Namespace }}
  labels:
    tier: prometheus-networking
    component: prometheus-virtualservice
    chart: {{ template "prometheus.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  hosts:
  - "prometheus.{{ .Values.global.baseDomain }}"
  gateways:
  - {{ .Values.global.istio.gateway }}
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: {{ template "prometheus.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: 9090
    {{- if .Values.global.istio.virtualService.timeout }}
    timeout: {{ .Values.global.istio.virtualService.timeout }}
    {{- end }}
    {{- if .Values.global.istio.virtualService.retries }}
    retries:
      {{- toYaml .Values.global.istio.virtualService.retries | nindent 6 }}
    {{- end }}
{{- end }}
{{- end }}
