#############################
## Registry ServiceAccount ##
#############################
{{- if .Values.registry.serviceAccount.create }}
{{- if eq (include "registry.enabled" .) "true" }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.registry.serviceAccount.automountServiceAccountToken }}
metadata:
  name: {{ template "registry.serviceAccountName" . }}
  labels:
    {{- include "global.labels" . | nindent 4 }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    plane: {{ .Values.global.plane.mode }}
  annotations:
{{- toYaml .Values.registry.serviceAccount.annotations | nindent 4 }}
{{- end -}}
{{- end }}
