#################################
## Astronomer Registry Secrets ##
#################################
{{ if and .Values.global.baseDomain (not .Values.registry.auth.secretName) }}
{{- if eq (include "registry.enabled" .) "true" }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "registry.authSecret" . }}
  labels:
    {{- include "global.labels" . | nindent 4 }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    plane: {{ .Values.global.plane.mode }}
  {{ if .Values.global.argoCD.annotation.enabled }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  {{- end }}
type: kubernetes.io/dockerconfigjson
data:
  {{- if .Values.registry.auth.connection }}
  .dockerconfigjson: {{ .Values.registry.auth.connection }}
  {{- else }}
  .dockerconfigjson: {{ include "registry.docker.config" . | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
