#################################
## Astronomer Registry Ingress ##
#################################
{{- if and .Values.global.baseDomain .Values.global.perHostIngress.enabled }}
{{- if eq (include "registry.enabled" .) "true" }}
kind: Ingress
apiVersion: {{ template "apiVersion.Ingress" . }}
metadata:
  name: {{ template "registry.fullname" . }}-ingress
  labels:
    component: {{ template "registry.name" . }}-ingress
    tier: astronomer
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    plane: {{ .Values.global.plane.mode }}
  annotations:
    {{- if .Values.global.authSidecar.enabled  }}
{{- toYaml .Values.global.extraAnnotations | nindent 4 }}
    {{- else }}
    kubernetes.io/ingress.class: "{{ .Release.Name }}-nginx"
    {{- if .Values.global.extraAnnotations }}
{{- toYaml .Values.global.extraAnnotations | nindent 4 }}
    {{- end }}
    nginx.ingress.kubernetes.io/custom-http-errors: "404"
    {{- end }}
spec:
  {{- if .Values.global.tlsSecret }}
  tls:
    - secretName: {{ .Values.global.tlsSecret }}
      hosts:
        - {{ include "registry.ingressURL" . }}
  {{- end }}
  rules:
  - host: {{ include "registry.ingressURL" . }}
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ template "registry.fullname" . }}
              port:
                name: registry-http
{{- end }}
{{- end }}
