################################
## Laminar Hypervisor Service ##
################################
{{- if eq (include "hibernator.enabled" .) "true" }}
kind: Service
apiVersion: v1
metadata:
  name: hypervisor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hibernator.labels" (list $ "hypervisor") | nindent 4 }}
    app.kubernetes.io/name: hypervisor
spec:
  type: ClusterIP
  selector:
    {{- include "hibernator.selectorLabels" (list $ "hypervisor") | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.hypervisor.port }}
      targetPort: http
{{- end }}
