########################################
## Laminar Hypervisor ServiceMonitor ##
########################################
{{- if eq (include "hibernator.enabled" .) "true" }}
{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: laminar-hypervisor
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hibernator.labels" (list $ "hypervisor") | nindent 4 }}
spec:
  endpoints:
    - path: {{ .Values.serviceMonitor.path }}
      port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: hypervisor
{{- end }}
{{- end }}
