{{- if .Values.global.istioEnabled }}
{{- if eq .Values.global.plane.mode "data" }}
---
apiVersion: {{ template "apiVersion.istio.networking" . }}
kind: VirtualService
metadata:
  name: {{ include "external-es-proxy.fullname" . }}-virtualservice
  namespace: {{ .Release.Namespace }}
  labels:
    tier: elasticsearch-networking
    component: external-es-proxy-virtualservice
    chart: {{ include "external-es-proxy.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  hosts:
  - "elasticsearch.{{ .Values.global.plane.domainPrefix }}.{{ .Values.global.baseDomain }}"
  gateways:
  - {{ .Values.global.istio.gateway }}
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: {{ include "external-es-proxy.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ .Values.httpPort }}
    {{- if .Values.global.istio.virtualService.timeout }}
    timeout: {{ .Values.global.istio.virtualService.timeout }}
    {{- end }}
    {{- if .Values.global.istio.virtualService.retries }}
    retries:
      {{- toYaml .Values.global.istio.virtualService.retries | nindent 6 }}
    {{- end }}
{{- end }}
{{- end }}
