{{- if .Values.global.istioEnabled }}
{{- if or (eq .Values.global.plane.mode "control") (eq .Values.global.plane.mode "unified") }}
---
apiVersion: {{ template "apiVersion.istio.networking" . }}
kind: VirtualService
metadata:
  name: {{ .Release.Name }}-houston-virtualservice
  namespace: {{ .Release.Namespace }}
  labels:
    component: istio-virtualservice
    tier: astronomer
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
spec:
  hosts:
  - "houston.{{ .Values.global.baseDomain }}"
  gateways:
  - {{ .Values.global.istio.gateway }}
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: {{ .Release.Name }}-houston.{{ .Release.Namespace }}.svc.cluster.local
        port:
          number: {{ .Values.ports.houstonHTTP }}
    {{- if .Values.global.istio.virtualService.timeout }}
    timeout: {{ .Values.global.istio.virtualService.timeout }}
    {{- end }}
    {{- if .Values.global.istio.virtualService.retries }}
    retries:
      {{- toYaml .Values.global.istio.virtualService.retries | nindent 6 }}
    {{- end }}
{{- end }}
{{- end }}
