###############################
## Containerd toml ConfigMap ##
###############################
{{- if and .Values.global.privateCaCertsAddToHost.enabled .Values.global.privateCaCertsAddToHost.addToContainerd }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-containerd-ca-config
  labels:
    component: houston
    tier: astronomer
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
data:
  update-containerd-certs.py: |-
{{ .Files.Get "files/update-containerd-certs.py" | indent 4 }}
  {{- with .Values.global.privateCaCertsAddToHost.containerdConfigToml }}
  containerd-config-toml: |-
    {{- include "containerd.configToml" $ | nindent 4 }}
  {{- end }}
{{- end }}