################################################
## Cluster-Local Service Auth Shared Secret   ##
################################################
{{- if or (eq .Values.global.plane.mode "data") (eq .Values.global.plane.mode "unified") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-cluster-local-service-auth
  labels:
    component: cluster-local-service-auth
    tier: astronomer
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    plane: {{ .Values.global.plane.mode }}
type: Opaque
data:
  token: {{ include "astronomer.clusterLocalServiceToken" . | b64enc | quote }}
{{- end }}
