#####################
## laminar.env file ##
#####################
{{- if eq (include "laminar.enabled" .) "true" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Values.envConfigMap.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "laminar.labels" (list $ "laminar") | nindent 4 }}
data:
  laminar.env: |
    laminar_scaling__dry_run_strategy=NEVER
    laminar_apply_custom_ddl=True
    laminar_hypervisor__enable_healers=False
    laminar_hypervisor__enable_health_incidents=False
    laminar_hypervisor__configmap_metrics_enabled=False
    laminar_hypervisor__configmap_metrics_use_informer=False
    laminar_hypervisor__queued_task_second_threshold=480
    laminar_hypervisor__disabled_metrics_csv=""
    laminar_hypervisor__dry_run_healers_csv=CatatonicWorkerTerminator
{{ .Values.envConfigMap.content | default "" | indent 4 }}
{{- end }}
