#####################
## laminar.env file ##
#####################
{{- if eq (include "laminar.enabled" .) "true" }}
{{- if and .Values.envConfigMap.enabled .Values.envConfigMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.envConfigMap.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "laminar.labels" (list $ "laminar") | nindent 4 }}
data:
  laminar.env: |
    laminar_enable_healers: False
    laminar_enable_health_incidents: False
    laminar_configmap_metrics_enabled: False
    laminar_configmap_metrics_use_informer: False
    laminar_dry_run_strategy: NEVER
{{ .Values.envConfigMap.content | indent 4 }}
{{- end }}
{{- end }}
