###############################
## Laminar database connection ##
###############################
{{- if eq (include "laminar.enabled" .) "true" }}
{{- if .Values.database.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "laminar.labels" (list $ "laminar") | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.database.secretKey }}: {{ required "database.connectionString is required when database.create is true" .Values.database.connectionString | quote }}
{{- end }}
{{- end }}
