###############################
## Laminar database connection ##
###############################
{{- if eq (include "laminar.enabled" .) "true" }}
{{- if and .Values.database.create .Values.database.connectionString }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.database.secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "laminar.labels" (list $ "laminar") | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.database.secretKey }}: {{ .Values.database.connectionString | quote }}
{{- end }}
{{- end }}
