##########################
## Laminar API Server ##
##########################
{{- if eq (include "laminar.enabled" .) "true" }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "laminar.fullname" (list $ "api-server") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "laminar.labels" (list $ "apiserver") | nindent 4 }}
spec:
  progressDeadlineSeconds: {{ .Values.apiServer.progressDeadlineSeconds }}
  replicas: {{ .Values.apiServer.replicas }}
  selector:
    matchLabels:
      {{- include "laminar.selectorLabels" (list $ "apiserver") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "laminar.selectorLabels" (list $ "apiserver") | nindent 8 }}
        {{- include "global.podLabels" . | nindent 8 }}
    spec:
      restartPolicy: Always
      serviceAccountName: {{ include "laminar.serviceAccountName" (list $ "api-server") }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      nodeSelector: {{ toYaml (default .Values.global.platformNodePool.nodeSelector .Values.nodeSelector) | nindent 8 }}
      affinity: {{ toYaml (default .Values.global.platformNodePool.affinity .Values.affinity) | nindent 8 }}
      tolerations: {{ toYaml (default .Values.global.platformNodePool.tolerations .Values.tolerations) | nindent 8 }}
      securityContext: {{- include "platform.podSecurityContext" (list $ nil) | nindent 8 }}
      {{- include "laminar.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: apiserver
          image: {{ include "laminar.image" . }}
          imagePullPolicy: {{ .Values.images.laminar.pullPolicy }}
          securityContext: {{- include "platform.containerSecurityContext" (list $ nil) | nindent 12 }}
          command:
            - "python"
            - "-m"
            - "laminar"
            - "api-server"
          resources: {{- toYaml .Values.apiServer.resources | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.apiServer.port }}
          env:
            {{- include "laminar.env" (list $ .Values.apiServer) | nindent 12 }}
          {{- with .Values.apiServer.livenessProbe }}
          livenessProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.apiServer.readinessProbe }}
          readinessProbe: {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- include "laminar.envVolumeMount" . | nindent 12 }}
      volumes:
        {{- include "laminar.envVolume" . | nindent 8 }}
      dnsConfig:
        options:
          - name: ndots
            value: "4"
{{- end }}
