##################################
## Laminar API Server NetworkPolicies ##
##################################
{{- if eq (include "laminar.enabled" .) "true" }}
{{- if .Values.global.networkPolicy.enabled }}
{{- $port := .Values.apiServer.port }}
{{- range $name, $ns := dict "allow-istio-ingress" "istio-system" "allow-symphony-ingress" "symphony" "allow-keda-ingress" "keda" }}
---
# allow traffic from the {{ $ns }} namespace to the api server
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "laminar.labels" (list $ "apiserver") | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "laminar.selectorLabels" (list $ "apiserver") | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ $ns }}
      ports:
        - protocol: TCP
          port: {{ $port }}
{{- end }}
{{- end }}
{{- end }}
