##########################
## Laminar API Server Service ##
##########################
{{- if eq (include "hibernator.enabled" .) "true" }}
kind: Service
apiVersion: v1
metadata:
  name: apiserver
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hibernator.labels" (list $ "apiserver") | nindent 4 }}
    app.kubernetes.io/name: apiserver
spec:
  type: ClusterIP
  selector:
    {{- include "hibernator.selectorLabels" (list $ "apiserver") | nindent 4 }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.apiServer.port }}
      targetPort: http
{{- end }}
