---
# This is for generating images, not for testing. There may be invalid configurations in here.
astronomer:
  flightDeck:
    enabled: true
  pilot:
    enabled: true
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
global:
  airflowOperator:
    enabled: true
  authSidecar:
    enabled: true
  baseDomain: foo.com
  customLogging:
    awsSecretName: dummy
    enabled: true
  dagOnlyDeployment:
    enabled: true
  loggingSidecar:
    enabled: true
  networkPolicy:
    enabled: true
  pgbouncer:
    enabled: true
  plane:
    mode: data
  podDisruptionBudgetsEnabled: true
  postgresqlEnabled: true
  privateCaCertsAddToHost:
    addToContainerd: true
    enabled: true
  prometheusPostgresExporterEnabled: true
  rbacEnabled: true
  taskUsageMetricsEnabled: true
nats:
  nats:
    exporter:
      enabled: true
    reloader:
      enabled: true
    jetStream:
      enabled: true
external-secrets:
  enabled: true
postgresql:
  replication:
    enabled: true
