global:
  namespaceLabels:
    # https://kubernetes.io/docs/concepts/security/pod-security-admission/#pod-security-admission-labels-for-namespaces
    pod-security.kubernetes.io/enforce: "restricted"  # available values: privileged, baseline, restricted
