astronomer:
  airflowChartVersion: 1.17.26-build39929
  commander:
    env:
      - name: COMMANDER_EXTERNAL_SECRET_MANAGER_SECRET_NAME
        value: secrets-backend-credentials
  dpLink:
    enabled: true
  flightDeck:
    enabled: true
  houston:
    worker:
      dispatcher:
        enabled: true
  images:
    astroUI:
      pullPolicy: Always
      tag: feature_apc-dr
    commander:
      pullPolicy: Always
      tag: feature_apc-dr
    houston:
      pullPolicy: Always
      tag: feature_apc-dr
  navigator:
    enabled: true
    env:
      - name: DEBUG
        value: "true"
  pilot:
    enabled: true
external-secrets:
  enabled: true
global:
  dataPlaneFailover:
    enabled: true
  helmRepo: https://internal-helm.astronomer.io
  prometheusPostgresExporterEnabled: false
  rbacEnabled: true
  ssl:
    enabled: true
    mode: disable
tags:
  logging: false
  monitoring: false
