astronomer:
  houston:
    strictSchemaCheck:
      enabled: true
#   dpLink:
#     enabled: true
#   flightDeck:
#     enabled: true
#   houston:
#     worker:
#       dispatcher:
#         enabled: true
#   images:
#     astroUI:
#       pullPolicy: Always
#     commander:
#       pullPolicy: Always
#       tag: master
#     houston:
#       pullPolicy: Always
#       tag: main
#   navigator:
#     enabled: true
#     env:
#       - name: DEBUG
#         value: "true"
#   pilot:
#     enabled: true
external-secrets:
  enabled: true
global:
  dataPlaneFailover:
    enabled: true
    externalSecretManagerName: astronomer-cluster-secret-store
  helmRepo: https://internal-helm.astronomer.io
  rbac:
    enabled: true
  ssl:
    enabled: true
    mode: disable
  prometheusPostgresExporter:
    enabled: true
tags:
  logging: true
  monitoring: true
