# Reduce resources for local dev
---
prometheus:
  replicas: 1
  resources:
    requests:
      cpu: "0.5m"
      memory: "0.5Gi"
    limits:
      cpu: "0.5m"
      memory: "4Gi" # required for a large spike in memory usage
  configMapReloader:
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 2Gi

  filesdReloader:
    resources:
      requests:
        cpu: 500m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 2Gi


prometheus-postgresql-exporter:
  replicaCount: 1
  resources:
    requests:
      cpu: "0.1m"
      memory: "0.5Gi"
    limits:
      cpu: "0.1m"
      memory: "1Gi"
