##################################
## Navigator Service Account    ##
##################################
{{- if and .Values.navigator.enabled (or (eq .Values.global.plane.mode "control") (eq .Values.global.plane.mode "unified")) }}
{{- if and .Values.navigator.serviceAccount.create .Values.global.rbacEnabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "navigator.serviceAccountName" . }}
  labels:
    component: navigator
    tier: astronomer
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    plane: {{ .Values.global.plane.mode }}
  annotations:
    {{- with .Values.navigator.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
{{- end }}
