###########################################################
## Astronomer Elasticsearch Client Pod Disruption Budget ##
###########################################################
{{- if .Values.global.podDisruptionBudgets.enabled }}
{{- if eq (include "logging.enabled" .) "true" }}
apiVersion: {{ include "apiVersion.PodDisruptionBudget" . }}
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}-es-client-pdb
  labels:
    {{- include "global.labels" . | nindent 4 }}
    tier: logging
    component: {{ template "elasticsearch.name" . }}
    release: {{ .Release.Name }}
    role: client
spec:
  {{- if lt ( .Values.client.replicas | int ) 4 }}
  maxUnavailable: 1
  {{- else }}
  maxUnavailable: {{ .Values.client.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      tier: logging
      component: {{ template "elasticsearch.name" . }}
      release: {{ .Release.Name }}
      role: client
{{- end }}
{{- end }}
