##########################
## NGINX IngressClass ##
##########################
{{- if eq .Values.global.plane.mode "control" }}
{{- if not .Values.global.ingressClassName }}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .Release.Name }}-nginx
  labels:
    tier: {{ template "nginx.name" . }}
    component: cp-ingress-controller
    chart: {{ template "nginx.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    plane: {{ .Values.global.plane.mode }}
spec:
  controller: k8s.io/ingress-nginx
{{- end }}
{{- end }}
