###############################
## MCP Server ServiceAccount ##
###############################
{{- if .Values.mcpServer.serviceAccount.create }}
{{- if eq (include "mcpServer.enabled" .) "true" }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.mcpServer.serviceAccount.automountServiceAccountToken }}
metadata:
  name: {{ template "mcpServer.serviceAccountName" . }}
  labels:
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
    heritage: {{ .Release.Service }}
    plane: {{ .Values.global.plane.mode }}
  annotations:
{{- toYaml .Values.mcpServer.serviceAccount.annotations | nindent 4 }}
{{- end -}}
{{- end }}
