#############################
## DP-Link Service Account ##
#############################
{{- if eq .Values.global.plane.mode "control" }}
{{- if and (or .Values.dpLink.enabled .Values.global.dataPlaneFailover.enabled) .Values.dpLink.serviceAccount.create .Values.global.rbac.enabled }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.dpLink.serviceAccount.automountServiceAccountToken }}
metadata:
  name: {{ template "dpLink.serviceAccountName" . }}
  labels:
    {{- include "global.labels" . | nindent 4 }}
    component: dp-link
    tier: astronomer
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    plane: {{ .Values.global.plane.mode }}
  annotations:
    {{- with .Values.dpLink.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
{{- end }}
