##############################
## Operator ServiceAccount  ##
##############################
{{- if (include "operator.enabled" .) }}
{{ if and .Values.serviceAccount.create .Values.global.rbac.enabled  }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
metadata:
  name: {{ template "operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    tier: operator
    component: controller-manager
    chart: {{ template "operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
